name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # Thay đổi thành nhánh bạn muốn trigger workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Thay đổi theo version .NET của bạn

      # Restore dependencies cho dự án trong thư mục CoffeeHouseAPI
      - name: Restore dependencies
        run: dotnet restore CoffeeHouse.sln

      # Build dự án ASP.NET trong thư mục CoffeeHouseAPI
      - name: Build the project
        run: dotnet build CoffeeHouse.sln --configuration Release --no-restore

      # Login vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image từ Dockerfile trong thư mục CoffeeHouseAPI
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coffeehouse-api:latest -f CoffeeHouseAPI/Dockerfile CoffeeHouseAPI

      # Push Docker image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/coffeehouse-api:latest
