name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # Thay đổi thành nhánh bạn muốn trigger workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Thay đổi theo version .NET của bạn

      # Restore dependencies cho dự án trong thư mục CoffeeHouseAPI
      - name: Restore dependencies
        run: dotnet restore .

      # Build dự án ASP.NET trong thư mục CoffeeHouseAPI
      - name: Build CoffeeHouseLib
        run: dotnet build CoffeeHouseLib/CoffeeHouseLib.csproj --configuration Release

      - name: Build the project
        run: dotnet build CoffeeHouseAPI/CoffeeHouseAPI.csproj --configuration Release --no-restore

      # Login vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build Docker image với tag v1
      - name: Build Docker image
        run: |
          docker build -t phuoc194203/init:v1 .
  
      # Bước 4: Push Docker image lên Docker Hub với tag v1
      - name: Push Docker image
        run: |
          docker push phuoc194203/init:v1
